Fixed JobTracker configuration to find the NameNode
The JobTracker will write to local disk if it cannot find the
NameNode. This results in exceptions on remote TaskTrackers of the
form:

 java.io.FileNotFoundException: File file:/tmp/hadoop-USER/mapred/system/JOBID/jobToken does not exist.